image: gitpod/workspace-full

tasks:
  - name: Mysql server and Run PetClinic app
    init: |
          sudo apt update &&
          sudo apt install -y mysql-server &&
          sudo service mysql start &&
          sudo sleep 5 &&
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'petclinic';" &&
          ./mvnw clean install -U -DskipTests
    command: ./mvnw spring-boot:run


ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack

jetbrains:
  intellij:
    plugins:
      - com.haulmont.jpab
    prebuilds:
      version: both


